name: Build CocoaInput Native

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            name: "Ubuntu 22.04 x64"

          - os: windows-2022
            name: "Windows Server 2022 x64"

          - os: macos-14
            name: "macOS 14 (Universal)"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: '(Windows) Setup MSVC'
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: '(Windows) Build CocoaInput-lib'
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          mkdir build
          cd src\win
          nmake install

      - name: '(macOS) Build CocoaInput-lib'
        if: runner.os == 'macOS'
        run: ./build_macOS.sh

      - name: '(Linux X11) Build CocoaInput-lib'
        if: runner.os == 'Linux'
        run: ./build_X11.sh

      - name: '(Linux Wayland) Build caramelChat-lib'
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y libwayland-dev wayland-protocols
          ./build_Wayland.sh

      - name: Upload Library
        uses: actions/upload-artifact@v4
        with:
          name: CocoaInput-lib_${{ runner.os }}
          path: build/
